#开发常见问题请参考：http://doc.shtest.ke.com/common-knowledge/faq/dev101.html
#spring.application.name是应用（服务）的唯一标识，全局唯一，请使用一致、清晰易懂的命名
spring:
    application:
        name: store-vr-camera-server
    profiles:
        active: development
        
#如果你的项目需要用到Redis，请参考文档：http://doc.shtest.ke.com/infrastructure/redis/redis-springboot-project.html        
#如果你的项目需要用到Kafka，请参考文档：http://doc.shtest.ke.com/infrastructure/kafka/kafka-springboot-project.html
#如果你的项目需要用到MongoDB，请参考文档：http://doc.shtest.ke.com/infrastructure/mongodb/mongo-springboot-project.html

#显式启用Apollo，配置中心接入：http://doc.shtest.ke.com/infrastructure/spring-cloud/config.html
#除了development，其他环境(beta/test/off/production)建议放在Apollo配置中心
apollo.bootstrap.enabled: true
    